---
name: "hpeov-servers2-snow-rule"
description: "Get HPE OneView servers and send to service now."
enabled: false

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
    delta: 5
    unit: minutes

action:
  ref: "hpeoneview.hpeov-mongo-servers2-snow"
